---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность искать товары по ключевому категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары в корзине
  - Пользователь должен иметь возможность переключить язык интерфейса
  - ПОльзователь должен иметь возможность оформить заказ с последующим переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования
  - Сайт нужно разработать оптимизировать для скорости работы
  - Сайт должен быть безопасным
  - Сайт должен защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть совместим с последними версиями браузера
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть SPA-приложением
  - Корзина должна хранится в сессии браузера
implicit:
  - Пользователь не должен иметь возможности редактировать описание, цену, рейтинг товаров
  - Пользователь не должен иметь возможности добавлять свой товар в каталог магазина
