---
functional:
    Пользователь должен иметь возможность искать товары по ключевому слову или категории
    Пользователь должен иметь возможность искать товары по ключевому категории
    Пользователь должен иметь возможность фильтровать товары
    Пользователь должен иметь возможность просматривать товары 
    Пользователь должен иметь возможность просматривать подробную информацию о товаре
    Пользователь должен иметь возможность добавлять товары в корзину 
    Пользователь должен иметь возможность просматривать содержимое корзины
    Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
    Сайт нужно разработать с учетом удобства использования
    Сайт нужно разработать оптимизировать для скорости работы
    Сайт должен быть безопасным 
    Сайт должен защищать данные пользователя
    Сайт должен иметь мобильную версию
    Сайт должен быть совместим с последними версиями браузера
    Сайт должен обрабатывать большое количество трафика
    Сайт должен быть доступен на различных устройствах
    Сайт должен иметь локализацию (перевод) на русский язык
    Сайт должен иметь локализацию (перевод) на английский язы
    Сайт должен быть SPA-приложением
implicit:
    Корзина должна хранится в сессии браузера    
    Пользователь должен иметь возможность осуществлять заказ товаров ранее добавленных в корзину
    Пользователь должен иметь возможность удалять товары в корзине